### ISSUE TITLE
Overall accuracy (52.6) in Table 1 different from the highest EM@1 result (50.9) in the ablation experiment

### ISSUE THREAD

**Issue by LZ-CH** [YunzeMan/Situation3D#3]
Thank you for your great work. I would like to ask a question. In the paper, why is the Overall accuracy (52.6) in Table 1 different from the highest EM@1 result (50.9) in the ablation experiment? Is there a difference in the configuration?

**Comment by YunzeMan** [comment]
Thanks for your question. Best overall accuracy was obtained with a Large Multi-modal Transformer Decoder following [3D-LLM](https://github.com/UMass-Foundation-Model/3D-LLM/tree/main/3DLLM_BLIP2-base). For ablations, we use a shallow transformer decoder for fast evaluation, following ScanQA and [SQA3D](https://github.com/SilongYong/SQA3D) baselines.
